name: "Setup Genesyscloud Archy"
description: "Sets up Genesyscloud Archy in your GitHub Actions workflow."
author: "Steffen Schmidt"
inputs:
  archy-version:
    description: "The version of Genesyscloud Archy to install."
    default: "latest"
    required: false
runs:
  using: "node24"
  main: "dist/index.js"
branding:
  icon: "play"
  color: "blue"
